name: Node.js Package

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies (with build scripts)
        run: |
          pnpm config set auto-install-peers true
          pnpm install --ignore-scripts=false
        env:
          CI: false
      
      - name: Build
        run: pnpm run build
      
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}